[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "PySide6==6.2.2.1"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
